<a href="https://colab.research.google.com/github/Mayureshnema04/Mayuresh-Nema/blob/main/8th_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
data = {"Hours_studied": [1,2,3,4,5,6,7,8,9,10], "Attendance": [50,55,60,65,70,75,80,85,90,95], "Result": [0,0,0,0,1,1,1,1,1,1]}
df = pd.DataFrame(data)
df

   Hours_studied  Attendance  Result
0              1          50       0
1              2          55       0
2              3          60       0
3              4          65       0
4              5          70       1
5              6          75       1
6              7          80       1
7              8          85       1
8              9          90       1
9             10          95       1

In [11]:
X = df[["Hours_studied", "Attendance"]]
y = df["Result"]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [13]:
X_train

   Hours_studied  Attendance
2              3          60
7              8          85
1              2          55
8              9          90
0              1          50
3              4          65
5              6          75
9             10          95

In [14]:
y_train

2    0
7    1
1    0
8    1
0    0
3    0
5    1
9    1
Name: Result, dtype: int64

In [15]:
X_test

   Hours_studied  Attendance
6              7          80
4              5          70

In [16]:
y_test

6    1
4    1
Name: Result, dtype: int64

In [17]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [18]:
model.predict(X_test)

array([1, 0])

In [19]:
model.predict([[6,65]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [20]:
model.predict([[2,90]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [22]:
model.predict([[4.5,70]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [23]:
model.predict([[6,20]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [24]:
model.predict([[1,90]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [25]:
model.predict([[1,70]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [26]:
import pandas as pd
data = {"Hours_studied": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
        "Attendance": [5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100],
        "Result": [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1]
        }
df = pd.DataFrame(data)
df

    Hours_studied  Attendance  Result
0               1           5       0
1               2          10       0
2               3          15       0
3               4          20       0
4               5          25       0
5               6          30       0
6               7          35       0
7               8          40       0
8               9          45       1
9              10          50       1
10             11          55       1
11             12          60       1
12             13          65       1
13             14          70       1
14             15          75       1
15             16          80       1
16             17          85       1
17             18          90       1
18             19          95       1
19             20         100       1

In [27]:
X = df[["Hours_studied", "Attendance"]]
y = df["Result"]

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [29]:
X_train

    Hours_studied  Attendance
10             11          55
2               3          15
15             16          80
1               2          10
9              10          50
17             18          90
5               6          30
18             19          95
16             17          85
3               4          20
6               7          35
14             15          75
7               8          40
0               1           5
8               9          45
19             20         100

In [30]:
X_test

    Hours_studied  Attendance
13             14          70
4               5          25
12             13          65
11             12          60

In [31]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [32]:
model.predict(X_test)

array([1, 0, 1, 1])

In [33]:
model.predict([[6,65]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [36]:
model.predict(X_test)

array([0, 1, 1, 0])

In [37]:
X_test

    Hours_studied  Attendance
0               1           5
17             18          90
15             16          80
1               2          10

In [38]:
y_test

0     0
17    1
15    1
1     0
Name: Result, dtype: int64